language: ruby
cache: bundler
rvm:
- 2.3.0
before_install:
- openssl aes-256-cbc -K $encrypted_a631c1ae3253_key -iv $encrypted_a631c1ae3253_iv
  -in /home/g_seux/cookbooks/resource-weight/.travis/travis-ci.pem.enc -out ~\/cookbooks/resource-weight/.travis/travis-ci.pem
  -d
