# This file is auto-generated by the code_generator (one-time action)
#
# Cookbook Name:: resource-weight
# Spec:: default
#
# Copyright (c) 2016 Criteo

require 'spec_helper'

describe 'weight-test::default' do
  context 'When all attributes are default, on centos 7.2.1511' do
    let(:chef_run) do
      runner = ChefSpec::ServerRunner.new(
        platform: 'centos',
        version:  '7.2.1511',
      )
      runner.converge(described_recipe)
    end

    it 'converges successfully' do
      expect { chef_run }.to_not raise_error
    end

    describe 'default weight modification by attribute' do
      it 'sets default weight on reboot resource' do
        expect(chef_run).to cancel_reboot('another reboot').with(weight: 1)
      end

      it 'does not override reboot resource weight' do
        expect(chef_run).to cancel_reboot('why not?').with(weight: 5)
      end
    end
  end
  context 'When all attributes are default, on windows 6.3.9600' do
    let(:chef_run) do
      runner = ChefSpec::ServerRunner.new(
        platform: 'windows',
        version:  '2012R2',
      )
      runner.converge(described_recipe)
    end

    it 'converges successfully' do
      expect { chef_run }.to_not raise_error
    end
  end
end
