name             'weight-test'
maintainer       'Criteo SREs'
maintainer_email 'sre-core@criteo.com'
license          'Apache License'
description      'Test cookbook'
long_description 'Test cookbook'
version          '0.1.0'
# it should actually support every platform
supports         'centos'
supports         'windows'
depends          'resource-weight'
